# Generated by Django 3.2.15 on 2023-03-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('colour', models.ForeignKey(default='Tomato', on_delete=django.db.models.deletion.CASCADE, to='ca298shop.colour')),
                ('size', models.ForeignKey(default='Medium', on_delete=django.db.models.deletion.CASCADE, to='ca298shop.size')),
                ('type', models.ForeignKey(default='Regular', on_delete=django.db.models.deletion.CASCADE, to='ca298shop.type')),
            ],
        ),
    ]
